---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64

steps:
  - name: build
    image: golang:1.17
    commands:
      - go mod vendor
      - make
      - mkdir -p dist
      - cp lexa dist/lexa-$(uname -m)
  - name: pre_package
    depends_on:
      - build
    image: charlesportwoodii/ubuntu:20.04-build
    commands:
        - mkdir -p package
        - mkdir -p package/etc/systemd/system
        - mkdir -p package/etc/lexa
        - mkdir -p package/usr/local/bin
        - cp lexa package/usr/local/bin/lexa
        - cp lexa.service package/etc/systemd/system/lexa.service
        - ls -laht
  - name: package_debian
    depends_on:
      - pre_package
    image: charlesportwoodii/ubuntu:20.04-build
    commands:
      - fpm -s dir -t deb -n lexa -v ${DRONE_TAG}-$(uname -m) -C $(pwd)/package -p $(pwd)/dist/lexa-${DRONE_TAG}-$(uname -m).deb -m "charlesportwoodii@erianna.com" --license "proprietary" --url "https://github.com/kaidyth/lexa" --description "Lexa - instance and service discovery for LXD containers" --vendor "Kaidyth" --deb-systemd-restart-after-upgrade --template-scripts --force --no-deb-auto-config-files --deb-compression=gz
  - name: package_alpine
    depends_on:
      - pre_package
    image: charlesportwoodii/alpine:3.14-build
    commands:
      - fpm -s dir -t apk -n lexa -v ${DRONE_TAG}-$(uname -m) -C $(pwd)/package -p $(pwd)/dist/lexa-${DRONE_TAG}-$(uname -m).apk -m "charlesportwoodii@erianna.com" --license "proprietary" --url "https://github.com/kaidyth/lexa" --description "Lexa - instance and service discovery for LXD containers" --vendor "Kaidyth" --force
  - name: github-publish
    image: plugins/github-release
    depends_on:
      - package_debian
      - package_alpine
    when:
      event:
        - tag
    settings:
      api_key:
        from_secret: GITHUB_API_KEY
      files:
        - dist/*
      title: ${DRONE_TAG}
      checksum:
        - sha256
        - sha512
---
kind: pipeline
type: docker
name: build-arm64

platform:
  arch: arm64

steps:
  - name: build
    image: golang:1.17
    commands:
      - go mod vendor
      - make
      - mkdir -p dist
      - cp lexa dist/lexa-$(uname -m)
  - name: pre_package
    depends_on:
      - build
    image: charlesportwoodii/ubuntu:20.04-build
    commands:
        - mkdir -p package
        - mkdir -p package/etc/systemd/system
        - mkdir -p package/etc/lexa
        - mkdir -p package/usr/local/bin
        - cp lexa package/usr/local/bin/lexa
        - cp lexa.service package/etc/systemd/system/lexa.service
        - ls -laht
  - name: package_debian
    depends_on:
      - pre_package
    image: charlesportwoodii/ubuntu:20.04-build
    commands:
      - fpm -s dir -t deb -n lexa -v ${DRONE_TAG}-$(uname -m) -C $(pwd)/package -p $(pwd)/dist/lexa-${DRONE_TAG}-$(uname -m).deb -m "charlesportwoodii@erianna.com" --license "proprietary" --url "https://github.com/kaidyth/lexa" --description "Lexa - instance and service discovery for LXD containers" --vendor "Kaidyth" --deb-systemd-restart-after-upgrade --template-scripts --force --no-deb-auto-config-files --deb-compression=gz
  - name: package_alpine
    depends_on:
      - pre_package
    image: charlesportwoodii/alpine:3.14-build
    commands:
      - fpm -s dir -t apk -n lexa -v ${DRONE_TAG}-$(uname -m) -C $(pwd)/package -p $(pwd)/dist/lexa-${DRONE_TAG}-$(uname -m).apk -m "charlesportwoodii@erianna.com" --license "proprietary" --url "https://github.com/kaidyth/lexa" --description "Lexa - instance and service discovery for LXD containers" --vendor "Kaidyth" --force
  - name: github-publish
    image: plugins/github-release
    depends_on:
      - package_debian
      - package_alpine
    when:
      event:
        - tag
    settings:
      api_key:
        from_secret: GITHUB_API_KEY
      files:
        - dist/*
      title: ${DRONE_TAG}
      checksum:
        - sha256
        - sha512