---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64

steps:
  - name: build
    image: golang:1.17
    commands:
      - go mod vendor
      - make
      - mkdir -p dist
      - cp lexa dist/lexa-$(uname -m)
  - name: package_debian
    image: charlesportwoodii/ubuntu:20.04-build
    depends_on:
      - build
    commands:
      - make fpm_debian
  - name: package_alpine
    image: charlesportwoodii/alpine:3.14-build
    depends_on:
      - build
    commands:
      - make fpm_alpine
  - name: github-publish
    image: plugins/github-release
    depends_on:
      - package_debian
      - package_alpine
    when:
      event:
        - tag
    settings:
      api_key:
        from_secret: GITHUB_API_KEY
      files:
        - dist/*
      title: ${DRONE_TAG}

---
kind: pipeline
type: docker
name: build-arm64

platform:
  arch: arm64

steps:
  - name: build
    image: golang:1.17
    commands:
      - go mod vendor
      - make
      - mkdir -p dist
      - cp lexa dist/lexa-$(uname -m)
  - name: package_debian
    image: charlesportwoodii/ubuntu:20.04-build
    depends_on:
      - build
    commands:
      - make fpm_debian
  - name: package_alpine
    image: charlesportwoodii/alpine:3.14-build
    depends_on:
      - build
    commands:
      - make fpm_alpine
  - name: github-publish
    image: plugins/github-release
    depends_on:
      - package_debian
      - package_alpine
    when:
      event:
        - tag
    settings:
      api_key:
        from_secret: GITHUB_API_KEY
      files:
        - dist/*
      title: ${DRONE_TAG}