---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64

steps:
  - name: build
    image: golang:1.17
    commands:
      - go mod vendor
      - make
  - name: pre_package
    depends_on:
      - build
    image: charlesportwoodii/ubuntu:20.04-build
    commands:
        - mkdir -p scratch
        - mkdir -p package/etc/systemd/system
        - mkdir -p package/etc/lexa
        - mkdir -p package/usr/local/bin
        - cp lexa package/usr/local/bin/lexa
        - cp lexa.service package/etc/systemd/system/lexa.service
  - name: package_debian
    depends_on:
      - pre_package
    image: charlesportwoodii/ubuntu:20.04-build
    commands:
      - fpm -s dir -t deb -n lexa -v 0.1.0-$(uname -m) -C ./package/ -p lexa-0.1.0-$(uname -m).deb -m "charlesportwoodii@erianna.com" --license "proprietary" --url "https://github.com/kaidyth/lexa" --description "Lexa - instance and service discovery for LXD containers" --vendor "Kaidyth" --deb-systemd-restart-after-upgrade --template-scripts --force --no-deb-auto-config-files --deb-compression=gz --workdir ./scratch
  - name: package_alpine
    depends_on:
      - pre_package
    image: charlesportwoodii/alpine:3.14-build
    commands:
      - fpm -s dir -t apk -n lexa -v 0.1.0-$(uname -m) -C ./package/ -p lexa-0.1.0-$(uname -m).deb -m "charlesportwoodii@erianna.com" --license "proprietary" --url "https://github.com/kaidyth/lexa" --description "Lexa - instance and service discovery for LXD containers" --vendor "Kaidyth" --force --workdir ./scratch

---
kind: pipeline
type: docker
name: build-arm64

platform:
  arch: arm64

steps:
  - name: build
    image: golang:1.17
    commands:
      - go mod vendor
      - make
  - name: pre_package
    depends_on:
      - build
    image: charlesportwoodii/ubuntu:20.04-build
    commands:
        - mkdir -p scratch
        - mkdir -p package/etc/systemd/system
        - mkdir -p package/etc/lexa
        - mkdir -p package/usr/local/bin
        - cp lexa package/usr/local/bin/lexa
        - cp lexa.service package/etc/systemd/system/lexa.service
  - name: package_debian
    depends_on:
      - pre_package
    image: charlesportwoodii/ubuntu:20.04-build
    commands:
      - fpm -s dir -t deb -n lexa -v 0.1.0-$(uname -m) -C ./package/ -p lexa-0.1.0-$(uname -m).deb -m "charlesportwoodii@erianna.com" --license "proprietary" --url "https://github.com/kaidyth/lexa" --description "Lexa - instance and service discovery for LXD containers" --vendor "Kaidyth" --deb-systemd-restart-after-upgrade --template-scripts --force --no-deb-auto-config-files --deb-compression=gz --workdir ./scratch
  - name: package_alpine
    depends_on:
      - pre_package
    image: charlesportwoodii/alpine:3.14-build
    commands:
      - fpm -s dir -t apk -n lexa -v 0.1.0-$(uname -m) -C ./package/ -p lexa-0.1.0-$(uname -m).deb -m "charlesportwoodii@erianna.com" --license "proprietary" --url "https://github.com/kaidyth/lexa" --description "Lexa - instance and service discovery for LXD containers" --vendor "Kaidyth" --force --workdir ./scratch